server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://91.225.131.201:32768/drunkards
    username: postgres
    password: postgres
  profiles:
    active: ${profile:stub}