server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:32768/drunkards
    username: postgres
    password: postgres
  profiles:
    active: ${profile:stub}
logging:
  level:
    root: warn
    com:
      jedakah: debug
    org:
      springframework:
        security: debug
